spring:
  application:
    name: Adocao
  datasource:
    url: ${VETCARE_ADOCOES_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  server:
    error:
      include-stacktrace: never