spring:
  datasource:
    url: ${DATASOURCE_URL_VETCARE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  security:
    token:
      secret: ${TOKEN_PASSWORD}