spring:
  datasource:
    url: ${VETCARE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  security:
    token:
      secret: ${TOKEN_PASSWORD}